#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2019 Ericsson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

if [ $# -eq 0 ] || [ $(grep -c -i "$*" $OVE_PROJECT_DIR/schedule) -eq 0 ]; then
	cat $OVE_PROJECT_DIR/schedule | tr -d '|'
	exit 0
elif [ $(grep -c -i "$*" $OVE_PROJECT_DIR/schedule) -gt 1 ]; then
	grep -i "$*" $OVE_PROJECT_DIR/schedule
	exit 0
fi

url="$(grep -i "$*" $OVE_PROJECT_DIR/schedule | cut -d'|' -f2)"
if ! command -V xdg-open &> /dev/null; then
	echo $url
	exit 0
fi

set -x
setsid -w xdg-open $url
